#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ExampleApplication.Resource", IsApplication=true)]

namespace ExampleApplication
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050007
			public const int ButtonSend = 2131034119;
			
			// aapt resource value: 0x7f050002
			public const int ButtonStart = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int EditMessage = 2131034118;
			
			// aapt resource value: 0x7f050001
			public const int EditName = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int LayoutChatView = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int LayoutConnectDisconnect = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int LayoutSendMessage = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int TextConsole = 2131034117;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040006
			public const int AlertNotConnected = 2130968582;
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int ButtonConnect = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int ButtonDisconnect = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int ButtonSend = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int FormatHintEnterMessage = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int HintEnterName = 2130968577;
			
			// aapt resource value: 0x7f040007
			public const int ToastDisconnected = 2130968583;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
